/* Generated by lastchange.py, do not edit.*/

#ifndef SKIA_EXT_SKIA_COMMIT_HASH_H_
#define SKIA_EXT_SKIA_COMMIT_HASH_H_

#define SKIA_COMMIT_HASH "86bb2f25f46f4d620b4a26e738f59a9b6c22d2eb"

#endif  // SKIA_EXT_SKIA_COMMIT_HASH_H_
