/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_WEBGPU_DAWN_COMMIT_HASH_H_
#define GPU_WEBGPU_DAWN_COMMIT_HASH_H_

#define DAWN_COMMIT_HASH "48d9737ff728e6211290d591b203a44cb77a2cc5"

#endif  // GPU_WEBGPU_DAWN_COMMIT_HASH_H_
